export const products = {
  solarGenerators: [
    {
      id: 'ecoflow-delta-pro',
      name: 'EcoFlow Delta Pro',
      brand: 'EcoFlow',
      category: 'Solar Generators',
      capacity: 3600,
      output: 3600,
      price: 1999,
      oldPrice: 2299,
      weight: 99,
      dimensions: '25 x 11.5 x 16.4 inches',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Expandable', 'Smart App', 'High Capacity'],
      affiliateUrl: 'https://amzn.to/4xhnROx',
      image: '/images/products/ecoflow-delta-pro.jpg',
      rating: 4.8,
      reviews: 1243,
      badge: 'Best Overall',
      description: 'The EcoFlow Delta Pro is the most powerful portable power station we\'ve ever tested. With 3,600Wh capacity and expandability up to 25kWh, it can power an entire home during a multi-day outage. The 3,600W output handles heavy appliances like refrigerators, sump pumps, and medical equipment with ease.',
      pros: ['Huge 3.6kWh capacity', 'Powerful 3600W output', 'Fast charging (0-80% in 1.8hrs)', '5-year warranty', 'Expandable to 25kWh', 'Smart app controls'],
      cons: ['Very heavy (99 lbs)', 'Expensive upfront', 'Requires extra battery for expansion'],
      bestFor: 'Home backup, emergency preparedness, off-grid living',
      runtimeEstimate: '20+ hours refrigerator'
    },
    {
      id: 'bluetti-ac200max',
      name: 'Bluetti AC200MAX',
      brand: 'Bluetti',
      category: 'Solar Generators',
      capacity: 2048,
      output: 2200,
      price: 1448,
      oldPrice: 1799,
      weight: 62,
      dimensions: '16.5 x 11 x 15.2 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Expandable', 'LCD Display', 'Wireless Charging'],
      affiliateUrl: 'https://amzn.to/4y5cdqA',
      image: '/images/products/bluetti-ac200max.jpg',
      rating: 4.7,
      reviews: 892,
      badge: 'Best Value',
      description: 'The Bluetti AC200MAX offers incredible value at $1,099. With 2,048Wh capacity and 2,200W output, it handles most home backup needs at 45% less cost than the Delta Pro. The 62 lbs weight makes it more portable, and the built-in wireless charging is a nice touch.',
      pros: ['Excellent value', 'Lighter at 62 lbs', 'Wireless charging', 'LCD display', 'Expandable with B230'],
      cons: ['Lower capacity', 'Shorter warranty (2 years)', 'No smart app'],
      bestFor: 'Budget-conscious buyers, camping, van life, emergency backup',
      runtimeEstimate: '12-16 hours refrigerator'
    },
    {
      id: 'jackery-explorer-2000',
      name: 'Jackery Explorer 2000',
      brand: 'Jackery',
      category: 'Solar Generators',
      capacity: 2160,
      output: 2200,
      price: 1699,
      oldPrice: 1899,
      weight: 43.5,
      dimensions: '15.1 x 10.4 x 12.2 inches',
      warranty: '3 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Portable', 'Easy to Use', 'Solar Ready'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=explorer-2000',
      image: '/images/products/jackery-explorer-2000.jpg',
      rating: 4.9,
      reviews: 1567,
      badge: 'Most Portable',
      description: 'The Explorer 2000 is the most trusted brand in the industry, known for reliability and ease of use. Despite the high capacity, it weighs only 43.5 lbs and features a foldable handle, making it the best option for those who need to move their power station frequently.',
      pros: ['Lightweight for capacity', 'Excellent customer service', '3-year warranty', 'Proven reliability', 'Easy to use'],
      cons: ['Expensive per Wh', 'No expansion options', 'Fewer ports'],
      bestFor: 'Camping, RV travel, portable backup power',
      runtimeEstimate: '14-20 hours refrigerator'
    },
    {
      id: 'ecoflow-delta-2',
      name: 'EcoFlow Delta 2',
      brand: 'EcoFlow',
      category: 'Solar Generators',
      capacity: 1024,
      output: 1800,
      price: 899,
      oldPrice: 999,
      weight: 27,
      dimensions: '15.7 x 8.3 x 11.1 inches',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Compact', 'Fast Charging', 'Expandable'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=delta-2',
      image: '/images/products/ecoflow-delta-2.jpg',
      rating: 4.8,
      reviews: 756,
      badge: 'Compact Power',
      description: 'The EcoFlow Delta 2 packs 1,024Wh capacity and 1,800W output into a compact unit. With fast charging and expandable options, it\'s perfect for home backup without taking up too much space.',
      pros: ['Compact size', 'High output', 'Expandable with extra batteries', '5-year warranty'],
      cons: ['Lower capacity than Delta Pro', 'Fans can be loud'],
      bestFor: 'Home backup, van life, CPAP backup',
      runtimeEstimate: '10-12 hours refrigerator'
    },
    {
      id: 'bluetti-ac200p',
      name: 'Bluetti AC200P',
      brand: 'Bluetti',
      category: 'Solar Generators',
      capacity: 2000,
      output: 2000,
      price: 899,
      oldPrice: 1099,
      weight: 60.6,
      dimensions: '16.5 x 11 x 15.2 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['High Capacity', 'Solar Ready', 'LCD Display'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=456&afftrack=ac200p',
      image: '/images/products/bluetti-ac200p.jpg',
      rating: 4.6,
      reviews: 678,
      badge: null,
      description: 'The Bluetti AC200P is a high-capacity power station with 2,000Wh and 2,000W output. It\'s a great option for home backup and off-grid use, with multiple charging options including solar.',
      pros: ['Large capacity', '2000W output', 'Multiple ports', 'Solar compatible'],
      cons: ['Heavy (60+ lbs)', '2-year warranty'],
      bestFor: 'Home backup, off-grid living, emergency power',
      runtimeEstimate: '14-18 hours refrigerator'
    },
    {
      id: 'jackery-explorer-1000',
      name: 'Jackery Explorer 1000',
      brand: 'Jackery',
      category: 'Solar Generators',
      capacity: 1002,
      output: 1000,
      price: 799,
      oldPrice: 999,
      weight: 22,
      dimensions: '13.1 x 9.2 x 11.1 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Portable', 'Reliable', 'Lightweight'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=explorer-1000',
      image: '/images/products/jackery-explorer-1000.jpg',
      rating: 4.8,
      reviews: 2345,
      badge: 'Best Seller',
      description: 'The Jackery Explorer 1000 is one of the most popular portable power stations. With 1,002Wh capacity and 1,000W output, it\'s perfect for camping, van life, and emergency backup. The 22 lbs weight makes it easy to move.',
      pros: ['Lightweight for capacity', 'Best-selling model', 'Reliable performance', 'Easy to use'],
      cons: ['No expansion option', '2-year warranty'],
      bestFor: 'Camping, van life, emergency backup',
      runtimeEstimate: '8-10 hours refrigerator'
    },
    {
      id: 'goal-zero-yeti-1500x',
      name: 'Goal Zero Yeti 1500X',
      brand: 'Goal Zero',
      category: 'Solar Generators',
      capacity: 1516,
      output: 2000,
      price: 1799,
      weight: 45.6,
      dimensions: '15.3 x 10.1 x 11.1 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Rugged', 'High Output', 'Expandable'],
      affiliateUrl: 'https://impact.com/goalzero?aff_id=YOUR_ID&offer=yeti-1500x',
      image: '/images/products/goal-zero-yeti-1500x.jpg',
      rating: 4.5,
      reviews: 456,
      badge: null,
      description: 'The Goal Zero Yeti 1500X is a rugged, high-output power station built for off-grid adventures and home backup. With 1,516Wh capacity and 2,000W output, it\'s a reliable choice for powering essential appliances.',
      pros: ['Rugged and durable', 'High output for its size', 'Expandable with Link modules', 'User-friendly display'],
      cons: ['Expensive', 'Heavy at 45.6 lbs', 'Shorter warranty'],
      bestFor: 'Off-grid living, camping, emergency backup',
      runtimeEstimate: '12-15 hours refrigerator'
    },
    {
      id: 'renogy-phoenix-1000',
      name: 'Renogy Phoenix 1000',
      brand: 'Renogy',
      category: 'Solar Generators',
      capacity: 998,
      output: 1000,
      price: 499,
      oldPrice: 699,
      weight: 23.4,
      dimensions: '13.4 x 7.5 x 10.2 inches',
      warranty: '3 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Budget Friendly', 'Portable', 'Solar Ready'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=phoenix-1000',
      image: '/images/products/renogy-phoenix-1000.jpg',
      rating: 4.4,
      reviews: 321,
      badge: 'Budget Pick',
      description: 'The Renogy Phoenix 1000 is the best budget-friendly power station with 1,000Wh capacity. It\'s perfect for those just getting started with solar power without breaking the bank.',
      pros: ['Affordable price', 'Good capacity for the cost', '3-year warranty', 'Solar compatible'],
      cons: ['Lower build quality', 'Slower charging times', 'Basic features'],
      bestFor: 'Budget-conscious buyers, beginners, camping',
      runtimeEstimate: '8-10 hours refrigerator'
    }
  ],
  portablePowerStations: [
    {
      id: 'ecoflow-river-2',
      name: 'EcoFlow River 2',
      brand: 'EcoFlow',
      category: 'Portable Power Stations',
      capacity: 256,
      output: 300,
      price: 199,
      oldPrice: 249,
      weight: 7.7,
      dimensions: '9.7 x 5.8 x 5.9 inches',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Compact', 'Fast Charging', 'Lightweight'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=river-2',
      image: '/images/products/ecoflow-river-2.jpg',
      rating: 4.6,
      reviews: 456,
      badge: 'Best Value',
      description: 'The River 2 is the perfect entry-level power station. Small enough for backpacking but powerful enough for weekend camping trips. With fast charging and 5-year warranty, it\'s the best portable option for small devices.',
      pros: ['Very lightweight (7.7 lbs)', 'Fast charging', '5-year warranty', 'Affordable price'],
      cons: ['Limited capacity', 'Not for large appliances'],
      bestFor: 'Light camping, phone charging, small electronics',
      runtimeEstimate: '2-3 hours phone charging'
    },
    {
      id: 'jackery-explorer-300',
      name: 'Jackery Explorer 300',
      brand: 'Jackery',
      category: 'Portable Power Stations',
      capacity: 293,
      output: 300,
      price: 299,
      weight: 7.1,
      dimensions: '9.1 x 5.2 x 7.7 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Portable', 'Reliable', 'Multiple Ports'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=explorer-300',
      image: '/images/products/jackery-explorer-300.jpg',
      rating: 4.7,
      reviews: 789,
      badge: 'Top Rated',
      description: 'The Jackery Explorer 300 is a compact, reliable power station that\'s perfect for short camping trips and outdoor adventures. With 293Wh capacity and 300W output, it\'s easy to carry and simple to use.',
      pros: ['Lightweight', 'Reliable brand', 'Multiple ports', 'Easy to use'],
      cons: ['Limited output', '2-year warranty', 'No fast charging'],
      bestFor: 'Short camping trips, small electronics, outdoor activities',
      runtimeEstimate: '3-4 hours phone charging'
    },
    {
      id: 'bluetti-eb3a',
      name: 'Bluetti EB3A',
      brand: 'Bluetti',
      category: 'Portable Power Stations',
      capacity: 268,
      output: 600,
      price: 249,
      oldPrice: 299,
      weight: 10.1,
      dimensions: '10 x 7.5 x 7.4 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Fast Charging', 'Compact', 'LCD Display'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=456&afftrack=eb3a',
      image: '/images/products/bluetti-eb3a.jpg',
      rating: 4.5,
      reviews: 345,
      badge: null,
      description: 'The Bluetti EB3A is a compact power station that punches above its weight. With 600W output from a 268Wh battery, it can handle small appliances and multiple devices simultaneously. Perfect for camping and short trips.',
      pros: ['600W high output for size', 'Fast charging', 'LCD display', 'Multiple USB ports'],
      cons: ['Limited capacity', 'Not for home backup'],
      bestFor: 'Camping, tailgating, small electronics',
      runtimeEstimate: '2-3 hours small fridge'
    },
    {
      id: 'jackery-explorer-500',
      name: 'Jackery Explorer 500',
      brand: 'Jackery',
      category: 'Portable Power Stations',
      capacity: 518,
      output: 500,
      price: 499,
      oldPrice: 599,
      weight: 13.3,
      dimensions: '11.8 x 7.6 x 9.2 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Portable', 'Reliable', 'Multiple Ports'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=explorer-500',
      image: '/images/products/jackery-explorer-500.jpg',
      rating: 4.7,
      reviews: 1892,
      badge: 'Best Seller',
      description: 'The Jackery Explorer 500 is one of the best-selling portable power stations. With 518Wh capacity and 500W output, it\'s perfect for camping trips, road trips, and emergency backup. Its lightweight design makes it easy to transport.',
      pros: ['Lightweight design', 'Reliable performance', 'Multiple charging options', 'Trusted brand'],
      cons: ['Limited output for large appliances', '2-year warranty'],
      bestFor: 'Camping, road trips, emergency backup',
      runtimeEstimate: '5-7 hours refrigerator'
    },
    {
      id: 'ecoflow-river-2-pro',
      name: 'EcoFlow River 2 Pro',
      brand: 'EcoFlow',
      category: 'Portable Power Stations',
      capacity: 768,
      output: 800,
      price: 499,
      oldPrice: 649,
      weight: 17.2,
      dimensions: '11.2 x 7.4 x 8.7 inches',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Fast Charging', 'Portable', 'High Output'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=river-2-pro',
      image: '/images/products/ecoflow-river-2-pro.jpg',
      rating: 4.8,
      reviews: 654,
      badge: 'New Release',
      description: 'The River 2 Pro is the upgraded version of the popular River 2. With 768Wh capacity and 800W output, it offers more power while still being portable. Fast charging gets you to 80% in just 1 hour.',
      pros: ['Fast charging (0-80% in 1hr)', 'High output for size', '5-year warranty', 'Expandable with batteries'],
      cons: ['Higher price than River 2', 'Heavier than other portables'],
      bestFor: 'Camping, van life, small appliance backup',
      runtimeEstimate: '7-9 hours refrigerator'
    },
    {
      id: 'goal-zero-yeti-500x',
      name: 'Goal Zero Yeti 500X',
      brand: 'Goal Zero',
      category: 'Portable Power Stations',
      capacity: 505,
      output: 300,
      price: 399,
      oldPrice: 499,
      weight: 11.5,
      dimensions: '7.6 x 6.0 x 8.1 inches',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Compact', 'Rugged', 'Reliable'],
      affiliateUrl: 'https://impact.com/goalzero?aff_id=YOUR_ID&offer=yeti-500x',
      image: '/images/products/goal-zero-yeti-500x.jpg',
      rating: 4.4,
      reviews: 234,
      badge: null,
      description: 'The Goal Zero Yeti 500X is a compact, rugged power station built for outdoor adventures. With 505Wh capacity and 300W output, it\'s perfect for camping, fishing, and off-grid activities.',
      pros: ['Compact and portable', 'Rugged design', 'User-friendly interface', 'Solar compatible'],
      cons: ['Low output for size', '2-year warranty', 'Pricier than competitors'],
      bestFor: 'Camping, fishing, outdoor activities, small electronics',
      runtimeEstimate: '4-5 hours refrigerator'
    }
  ],
  batteryBackups: [
    {
      id: 'renogy-battery',
      name: 'Renogy 100Ah Lithium Battery',
      brand: 'Renogy',
      category: 'Battery Backups',
      capacity: 1280,
      output: 1000,
      price: 699,
      oldPrice: 799,
      weight: 31.9,
      dimensions: '13.4 x 7.4 x 7.3 inches',
      warranty: '5 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar', 'AC'],
      features: ['Deep Cycle', 'Long Life', 'BMS Protection'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-battery',
      image: '/images/products/renogy-battery.jpg',
      rating: 4.5,
      reviews: 234,
      badge: 'Best Battery',
      description: 'The Renogy 100Ah lithium battery is perfect for building your own solar system. With deep cycle capability and BMS protection, it will last for years. Ideal for off-grid living and DIY solar projects.',
      pros: ['Long lifespan', 'BMS protection', 'Deep cycle capable', '5-year warranty'],
      cons: ['Requires external inverter', 'Installation required'],
      bestFor: 'DIY solar projects, off-grid living, home backup',
      runtimeEstimate: '8-10 hours refrigerator'
    },
    {
      id: 'battleborn-100ah',
      name: 'Battle Born 100Ah LiFePO4',
      brand: 'Battle Born',
      category: 'Battery Backups',
      capacity: 1280,
      output: 1000,
      price: 949,
      oldPrice: 1099,
      weight: 31,
      dimensions: '12.8 x 6.7 x 8.7 inches',
      warranty: '10 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar', 'AC'],
      features: ['Premium Quality', 'Longest Warranty', 'Built for Off-Grid'],
      affiliateUrl: 'https://impact.com/battleborn?aff_id=YOUR_ID&offer=100ah',
      image: '/images/products/battleborn-100ah.jpg',
      rating: 4.9,
      reviews: 178,
      badge: 'Premium',
      description: 'The Battle Born 100Ah battery is a premium lithium battery with the longest warranty in the industry. Built with top-quality cells and engineering, it\'s the best battery for serious off-grid systems.',
      pros: ['10-year warranty', 'Premium quality cells', 'Designed for off-grid', 'Excellent customer support'],
      cons: ['Premium price', 'Heavier than other options'],
      bestFor: 'Off-grid living, marine use, professional installations',
      runtimeEstimate: '8-10 hours refrigerator'
    },
    {
      id: 'lion-energy-100ah',
      name: 'Lion Energy 100Ah',
      brand: 'Lion Energy',
      category: 'Battery Backups',
      capacity: 1280,
      output: 1000,
      price: 599,
      oldPrice: 699,
      weight: 29.5,
      dimensions: '13.5 x 7.1 x 7.2 inches',
      warranty: '5 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar', 'AC'],
      features: ['Budget Friendly', 'Deep Cycle', 'Lightweight'],
      affiliateUrl: 'https://impact.com/lionenergy?aff_id=YOUR_ID&offer=100ah',
      image: '/images/products/lion-energy-100ah.jpg',
      rating: 4.6,
      reviews: 123,
      badge: 'Budget Pick',
      description: 'The Lion Energy 100Ah battery offers great value without compromising on quality. It\'s lightweight, reliable, and perfect for medium-sized solar installations.',
      pros: ['Affordable price', 'Lightweight design', 'BMS protection', '5-year warranty'],
      cons: ['Less premium than Battle Born', 'Limited reviews'],
      bestFor: 'Budget-conscious solar projects, RV upgrades, small cabins',
      runtimeEstimate: '8-10 hours refrigerator'
    },
    {
      id: 'ecoworthy-100ah',
      name: 'ECO-WORTHY 100Ah',
      brand: 'ECO-WORTHY',
      category: 'Battery Backups',
      capacity: 1280,
      output: 800,
      price: 299,
      oldPrice: 399,
      weight: 28.7,
      dimensions: '13.4 x 7.3 x 7.1 inches',
      warranty: '3 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar', 'AC'],
      features: ['Affordable', 'Deep Cycle', 'BMS Protection'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=ecoworthy-100ah',
      image: '/images/products/ecoworthy-100ah.jpg',
      rating: 4.3,
      reviews: 456,
      badge: 'Most Affordable',
      description: 'The ECO-WORTHY 100Ah battery is the most affordable lithium battery on the market. Perfect for budget solar setups and DIY projects where cost is the primary concern.',
      pros: ['Best price point', 'BMS protection', 'Deep cycle capable', 'Good for beginners'],
      cons: ['Lower quality cells', 'Shorter warranty (3 years)', 'Lower output'],
      bestFor: 'DIY solar projects, budget builds, beginners',
      runtimeEstimate: '6-8 hours refrigerator'
    }
  ],
  solarPanels: [
    {
      id: 'renogy-200w-solar-panel',
      name: 'Renogy 200W Monocrystalline Solar Panel',
      brand: 'Renogy',
      category: 'Solar Panels',
      capacity: 200,
      output: 200,
      price: 179,
      oldPrice: 229,
      weight: 26.5,
      dimensions: '64.6 x 26.4 x 1.4 inches',
      warranty: '25 years',
      ports: ['MC4 Connectors'],
      charging: ['Solar'],
      features: ['Monocrystalline', 'High Efficiency', 'Waterproof'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-200w',
      image: '/images/products/renogy-200w-solar-panel.jpg',
      rating: 4.8,
      reviews: 567,
      badge: 'Best Seller',
      description: 'The Renogy 200W solar panel is a high-efficiency monocrystalline panel perfect for home and off-grid systems. With 25-year warranty and waterproof design, it\'s built to last.',
      pros: ['High efficiency', '25-year warranty', 'Waterproof and durable', 'Great value'],
      cons: ['Heavy (26.5 lbs)', 'Requires MC4 connectors'],
      bestFor: 'Home solar, RV solar, off-grid systems',
      runtimeEstimate: '200W - 1.2kWh per day'
    },
    {
      id: 'ecoflow-400w-solar-panel',
      name: 'EcoFlow 400W Solar Panel',
      brand: 'EcoFlow',
      category: 'Solar Panels',
      capacity: 400,
      output: 400,
      price: 699,
      oldPrice: 799,
      weight: 30.9,
      dimensions: '67.3 x 29.3 x 1.2 inches',
      warranty: '12 years',
      ports: ['MC4 Connectors'],
      charging: ['Solar'],
      features: ['Foldable', 'High Efficiency', 'Portable'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=400w-solar',
      image: '/images/products/ecoflow-400w-solar-panel.jpg',
      rating: 4.7,
      reviews: 345,
      badge: 'Premium',
      description: 'The EcoFlow 400W solar panel delivers premium performance in a foldable design. Perfect for camping, RV trips, and backup power, it can charge a power station in just a few hours.',
      pros: ['Foldable and portable', 'High output (400W)', 'Premium build quality', 'Fast charging'],
      cons: ['Expensive', 'Heavy (30.9 lbs)', 'Shorter warranty (12 years)'],
      bestFor: 'RV travel, camping, emergency power',
      runtimeEstimate: '400W - 2.4kWh per day'
    },
    {
      id: 'jackery-solarsaga-100w',
      name: 'Jackery SolarSaga 100W',
      brand: 'Jackery',
      category: 'Solar Panels',
      capacity: 100,
      output: 100,
      price: 299,
      oldPrice: 349,
      weight: 10.3,
      dimensions: '47.2 x 20.9 x 1.2 inches',
      warranty: '3 years',
      ports: ['USB-C', 'USB-A', 'DC'],
      charging: ['Solar'],
      features: ['Foldable', 'Lightweight', 'Multiple Outputs'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=solarsaga-100w',
      image: '/images/products/jackery-solarsaga-100w.jpg',
      rating: 4.9,
      reviews: 890,
      badge: 'Most Portable',
      description: 'The Jackery SolarSaga 100W is the most portable solar panel with built-in USB ports for direct charging. Foldable and lightweight, it\'s perfect for backpacking and camping.',
      pros: ['Very lightweight (10.3 lbs)', 'Built-in USB ports', 'Foldable design', 'Direct charging'],
      cons: ['Lower output', 'Shorter warranty (3 years)', 'Expensive for the output'],
      bestFor: 'Backpacking, camping, hiking, small power stations',
      runtimeEstimate: '100W - 0.6kWh per day'
    }
  ],
  accessories: [
    {
      id: 'renogy-mppt-charge-controller',
      name: 'Renogy MPPT Charge Controller',
      brand: 'Renogy',
      category: 'Accessories',
      capacity: null,
      output: null,
      price: 129,
      oldPrice: 179,
      weight: 4.2,
      dimensions: '8.2 x 5.7 x 2.6 inches',
      warranty: '2 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar', 'AC'],
      features: ['MPPT Technology', 'LCD Display', 'Multiple Protection'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=mppt-controller',
      image: '/images/products/renogy-mppt-controller.jpg',
      rating: 4.7,
      reviews: 456,
      badge: 'Essential',
      description: 'The Renogy MPPT Charge Controller optimizes solar panel output for maximum efficiency. With LCD display and multiple protection features, it\'s essential for any solar system.',
      pros: ['MPPT technology for 30% more efficiency', 'LCD display', 'Overcharge protection', 'Temperature compensation'],
      cons: ['Requires installation', 'Not user-friendly for beginners'],
      bestFor: 'Solar system builders, off-grid installations',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'ecoflow-xt60-cable',
      name: 'EcoFlow XT60 Solar Cable',
      brand: 'EcoFlow',
      category: 'Accessories',
      capacity: null,
      output: null,
      price: 29,
      weight: 0.5,
      dimensions: '10 feet',
      warranty: '1 year',
      ports: ['XT60 Connector'],
      charging: ['Solar'],
      features: ['High Quality', 'Weather Resistant', 'Universal'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=xt60-cable',
      image: '/images/products/ecoflow-xt60-cable.jpg',
      rating: 4.8,
      reviews: 789,
      badge: null,
      description: 'The EcoFlow XT60 Solar Cable connects your solar panels to EcoFlow power stations. Made with high-quality materials and weather-resistant design for outdoor use.',
      pros: ['Weather resistant', 'Universal fit for EcoFlow', 'High quality construction', 'Easy to use'],
      cons: ['Only works with EcoFlow', 'Limited length (10 feet)'],
      bestFor: 'EcoFlow power station owners, solar setup',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'jackery-powersupply-adapter',
      name: 'Jackery Car Power Supply Adapter',
      brand: 'Jackery',
      category: 'Accessories',
      capacity: null,
      output: null,
      price: 29,
      weight: 0.3,
      dimensions: '12 inches',
      warranty: '1 year',
      ports: ['Car Cigarette', 'DC'],
      charging: ['Car'],
      features: ['Portable', 'Easy to Use', 'Reliable'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=car-adapter',
      image: '/images/products/jackery-car-adapter.jpg',
      rating: 4.6,
      reviews: 234,
      badge: null,
      description: 'The Jackery Car Power Supply Adapter lets you charge your Jackery power station from your car\'s cigarette lighter. Perfect for road trips and emergencies.',
      pros: ['Easy to use', 'Portable', 'Affordable', 'Reliable'],
      cons: ['Only works with Jackery', 'Slow charging rate'],
      bestFor: 'Jackery power station owners, road trips',
      runtimeEstimate: 'N/A'
    }
  ],
  inverters: [
    {
      id: 'renogy-1000w-inverter',
      name: 'Renogy 1000W Pure Sine Wave Inverter',
      brand: 'Renogy',
      category: 'Inverters',
      capacity: null,
      output: 1000,
      price: 129,
      oldPrice: 179,
      weight: 4.8,
      dimensions: '8.4 x 5.8 x 2.8 inches',
      warranty: '2 years',
      ports: ['AC', 'USB'],
      charging: ['DC'],
      features: ['Pure Sine Wave', 'Compact', 'USB Ports'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-1000w-inverter',
      image: '/images/products/renogy-1000w-inverter.jpg',
      rating: 4.6,
      reviews: 678,
      badge: 'Best Value',
      description: 'The Renogy 1000W Pure Sine Wave Inverter converts DC battery power to clean AC power for your appliances. Perfect for RV, marine, and off-grid applications. The compact design fits in tight spaces and the built-in USB ports add convenience.',
      pros: ['Pure sine wave output for sensitive electronics', 'Compact and lightweight', 'Built-in USB ports', 'Great value for the price'],
      cons: ['Limited to 1000W continuous power', '2-year warranty only'],
      bestFor: 'RV systems, marine applications, small off-grid setups',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-2000w-inverter',
      name: 'Renogy 2000W Pure Sine Wave Inverter',
      brand: 'Renogy',
      category: 'Inverters',
      capacity: null,
      output: 2000,
      price: 279,
      oldPrice: 349,
      weight: 8.2,
      dimensions: '11.8 x 7.3 x 3.5 inches',
      warranty: '2 years',
      ports: ['AC', 'USB'],
      charging: ['DC'],
      features: ['Pure Sine Wave', 'High Output', 'Remote Control'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-2000w-inverter',
      image: '/images/products/renogy-2000w-inverter.jpg',
      rating: 4.7,
      reviews: 456,
      badge: 'High Output',
      description: 'The Renogy 2000W inverter delivers clean, stable power for medium-sized appliances and RV systems. With remote control capability and pure sine wave output, it protects your sensitive electronics while providing ample power.',
      pros: ['2000W continuous power', 'Remote control included', 'Pure sine wave output', 'Good value for power output'],
      cons: ['Heavier than 1000W model', 'Requires proper ventilation', '2-year warranty'],
      bestFor: 'RV systems, off-grid homes, powering multiple appliances',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'ecoflow-smart-inverter',
      name: 'EcoFlow Smart Inverter',
      brand: 'EcoFlow',
      category: 'Inverters',
      capacity: null,
      output: 3000,
      price: 599,
      weight: 15.7,
      dimensions: '15.6 x 9.5 x 5.1 inches',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A'],
      charging: ['DC', 'Solar'],
      features: ['Smart App', 'Pure Sine Wave', 'High Efficiency'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=smart-inverter',
      image: '/images/products/ecoflow-smart-inverter.jpg',
      rating: 4.8,
      reviews: 345,
      badge: 'Premium',
      description: 'The EcoFlow Smart Inverter is a premium power conversion solution with app connectivity and solar input capability. Monitor and control your power usage from your phone while enjoying 3000W of clean, pure sine wave power.',
      pros: ['Smart app control', '3000W output capacity', 'Solar charging compatible', '5-year warranty'],
      cons: ['Premium price point', 'Heavy (15.7 lbs)', 'Requires EcoFlow ecosystem for full features'],
      bestFor: 'Home backup systems, EcoFlow power station expansion, professional installations',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'victron-800w-inverter',
      name: 'Victron Energy 800W Inverter',
      brand: 'Victron',
      category: 'Inverters',
      capacity: null,
      output: 800,
      price: 199,
      weight: 4.4,
      dimensions: '8.3 x 5.7 x 2.5 inches',
      warranty: '5 years',
      ports: ['AC', 'USB'],
      charging: ['DC'],
      features: ['Pure Sine Wave', 'Reliable', 'Compact'],
      affiliateUrl: 'https://impact.com/victron?aff_id=YOUR_ID&offer=800w-inverter',
      image: '/images/products/victron-800w-inverter.jpg',
      rating: 4.9,
      reviews: 234,
      badge: 'Most Reliable',
      description: 'The Victron Energy 800W inverter is renowned for its legendary reliability and build quality. It delivers clean, stable power for your essential devices with efficiency and durability that Victron is known for worldwide.',
      pros: ['Exceptional build quality', '5-year warranty', 'Highly reliable', 'Efficient power conversion'],
      cons: ['Lower output capacity', 'Premium price for the wattage', 'Limited features compared to smart inverters'],
      bestFor: 'Marine applications, off-grid systems, critical power needs',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-3000w-inverter',
      name: 'Renogy 3000W Pure Sine Wave Inverter',
      brand: 'Renogy',
      category: 'Inverters',
      capacity: null,
      output: 3000,
      price: 399,
      oldPrice: 499,
      weight: 11.5,
      dimensions: '13.6 x 8.1 x 3.5 inches',
      warranty: '2 years',
      ports: ['AC', 'USB'],
      charging: ['DC'],
      features: ['Pure Sine Wave', 'High Capacity', 'Parallel Capable'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-3000w-inverter',
      image: '/images/products/renogy-3000w-inverter.jpg',
      rating: 4.5,
      reviews: 567,
      badge: null,
      description: 'The Renogy 3000W inverter provides high-capacity power for demanding applications. With 3000W continuous output and 6000W surge capability, it handles heavy loads with ease. The parallel capability allows you to combine two units for even more power.',
      pros: ['3000W continuous power', 'Parallel capable for up to 6000W', 'Good price per watt', 'Surge capacity up to 6000W'],
      cons: ['Requires heavy cabling', 'Needs proper ventilation', '2-year warranty only'],
      bestFor: 'Whole-home backup, workshops, large RV systems',
      runtimeEstimate: 'N/A'
    }
  ],
  chargeControllers: [
    {
      id: 'renogy-mppt-30a',
      name: 'Renogy 30A MPPT Charge Controller',
      brand: 'Renogy',
      category: 'Charge Controllers',
      capacity: null,
      output: 30,
      price: 129,
      oldPrice: 179,
      weight: 4.2,
      dimensions: '9.2 x 6.6 x 2.5 inches',
      warranty: '2 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar'],
      features: ['MPPT Technology', 'LCD Display', 'Multiple Protection'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-mppt-30a',
      image: '/images/products/renogy-mppt-30a.jpg',
      rating: 4.7,
      reviews: 456,
      badge: 'Best Seller',
      description: 'The Renogy 30A MPPT charge controller maximizes your solar panel output with advanced tracking technology. The LCD display shows real-time data, and multiple protection features ensure your battery bank stays safe.',
      pros: ['MPPT technology for 30% more efficiency', 'Easy-to-read LCD display', 'Multiple protection features', 'Great value'],
      cons: ['Limited to 30A output', '2-year warranty', 'No Bluetooth connectivity'],
      bestFor: 'Small to medium solar systems, RVs, boats, off-grid cabins',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-mppt-40a',
      name: 'Renogy 40A MPPT Charge Controller',
      brand: 'Renogy',
      category: 'Charge Controllers',
      capacity: null,
      output: 40,
      price: 199,
      oldPrice: 249,
      weight: 4.8,
      dimensions: '10.2 x 7.2 x 2.8 inches',
      warranty: '2 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar'],
      features: ['MPPT Technology', 'Bluetooth', 'High Efficiency'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-mppt-40a',
      image: '/images/products/renogy-mppt-40a.jpg',
      rating: 4.8,
      reviews: 345,
      badge: null,
      description: 'The Renogy 40A MPPT charge controller offers higher capacity with Bluetooth monitoring. Track your solar production and battery status from your phone while getting maximum efficiency from your solar panels.',
      pros: ['40A output capacity', 'Bluetooth monitoring', 'High efficiency MPPT', 'Good value for features'],
      cons: ['Moderate price point', '2-year warranty', 'Bluetooth range limited'],
      bestFor: 'Medium-sized solar systems, home backup, commercial applications',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'victron-mppt-100-50',
      name: 'Victron SmartSolar MPPT 100/50',
      brand: 'Victron',
      category: 'Charge Controllers',
      capacity: null,
      output: 50,
      price: 299,
      weight: 3.5,
      dimensions: '9.3 x 6.5 x 3.1 inches',
      warranty: '5 years',
      ports: ['DC', 'Terminal', 'Bluetooth'],
      charging: ['Solar'],
      features: ['MPPT Technology', 'Bluetooth', 'Smart Monitoring'],
      affiliateUrl: 'https://impact.com/victron?aff_id=YOUR_ID&offer=mppt-100-50',
      image: '/images/products/victron-mppt-100-50.jpg',
      rating: 4.9,
      reviews: 789,
      badge: 'Premium',
      description: 'The Victron SmartSolar MPPT 100/50 is a premium charge controller with integrated Bluetooth monitoring. Track your system performance, adjust settings, and get alerts from your phone. Built with Victron\'s legendary quality and reliability.',
      pros: ['50A output capacity', 'Bluetooth connectivity', '5-year warranty', 'Victron quality and reliability'],
      cons: ['Premium price', 'Requires Victron ecosystem for full features', 'Advanced features may overwhelm beginners'],
      bestFor: 'Professional installations, high-end RV systems, marine applications',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'ecoflow-mppt-controller',
      name: 'EcoFlow MPPT Charge Controller',
      brand: 'EcoFlow',
      category: 'Charge Controllers',
      capacity: null,
      output: 35,
      price: 149,
      weight: 2.8,
      dimensions: '7.9 x 5.5 x 2.1 inches',
      warranty: '5 years',
      ports: ['DC', 'Terminal'],
      charging: ['Solar'],
      features: ['MPPT Technology', 'High Efficiency', 'Smart App'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=mppt-controller',
      image: '/images/products/ecoflow-mppt-controller.jpg',
      rating: 4.7,
      reviews: 456,
      badge: null,
      description: 'The EcoFlow MPPT charge controller is designed to work seamlessly with EcoFlow power stations. It delivers efficient solar charging with smart app integration for monitoring and control.',
      pros: ['35A output', 'EcoFlow app integration', '5-year warranty', 'Compact and lightweight'],
      cons: ['Limited to EcoFlow ecosystem', 'Less versatile than universal controllers', 'No display on unit'],
      bestFor: 'EcoFlow power station owners, solar charging setups',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-pwm-30a',
      name: 'Renogy 30A PWM Charge Controller',
      brand: 'Renogy',
      category: 'Charge Controllers',
      capacity: null,
      output: 30,
      price: 49,
      oldPrice: 69,
      weight: 1.5,
      dimensions: '6.5 x 4.2 x 1.8 inches',
      warranty: '1 year',
      ports: ['DC', 'Terminal'],
      charging: ['Solar'],
      features: ['PWM Technology', 'Basic Display', 'Budget Friendly'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-pwm-30a',
      image: '/images/products/renogy-pwm-30a.jpg',
      rating: 4.3,
      reviews: 234,
      badge: 'Budget Pick',
      description: 'The Renogy 30A PWM charge controller is the most affordable way to regulate solar charging. While it lacks the efficiency of MPPT controllers, it offers reliable basic protection at a fraction of the cost.',
      pros: ['Very affordable', 'Easy to install', 'Basic display for monitoring', 'Good for small systems'],
      cons: ['Less efficient than MPPT', '1-year warranty', 'Basic features only', 'No advanced monitoring'],
      bestFor: 'Budget solar projects, small systems, beginners, temporary setups',
      runtimeEstimate: 'N/A'
    }
  ],
  components: [
    {
      id: 'renogy-battery-cables',
      name: 'Renogy 2ft Battery Cables',
      brand: 'Renogy',
      category: 'Components',
      capacity: null,
      output: null,
      price: 19,
      weight: 0.8,
      dimensions: '2 ft',
      warranty: '1 year',
      ports: ['Terminal'],
      charging: [],
      features: ['Heavy Duty', 'Copper', 'Fused'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-cables',
      image: '/images/products/renogy-battery-cables.jpg',
      rating: 4.8,
      reviews: 567,
      badge: null,
      description: 'Renogy premium battery cables with ring terminals and built-in fuses. These heavy-duty copper cables ensure a reliable connection for your solar system with proper protection from the integrated fuse.',
      pros: ['Heavy-duty copper construction', 'Includes fuse holder for protection', 'Pre-terminated with ring ends', 'Easy installation'],
      cons: ['Short length (2 ft)', '1-year warranty', 'Limited gauge options'],
      bestFor: 'Connecting batteries, solar system wiring, inverter connections',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-inline-fuse',
      name: 'Renogy Inline Fuse Holder',
      brand: 'Renogy',
      category: 'Components',
      capacity: null,
      output: null,
      price: 12,
      weight: 0.3,
      dimensions: '10 inch',
      warranty: '1 year',
      ports: ['Terminal'],
      charging: [],
      features: ['Waterproof', 'Easy Install', 'Protection'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-fuse',
      image: '/images/products/renogy-inline-fuse.jpg',
      rating: 4.6,
      reviews: 234,
      badge: null,
      description: 'Protect your solar system with this waterproof inline fuse holder. Easy to install and compatible with standard fuse sizes, it provides essential safety protection for your electrical connections.',
      pros: ['Waterproof design', 'Easy installation', 'Versatile compatibility', 'Essential safety feature'],
      cons: ['Fuse not included in some packages', 'Basic design', '1-year warranty'],
      bestFor: 'Solar system protection, circuit protection, safety upgrades',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'victron-battery-monitor',
      name: 'Victron Smart Battery Monitor',
      brand: 'Victron',
      category: 'Components',
      capacity: null,
      output: null,
      price: 149,
      weight: 1.2,
      dimensions: '6.3 x 4.3 x 2.5 inches',
      warranty: '5 years',
      ports: ['Bluetooth', 'Terminal'],
      charging: [],
      features: ['Bluetooth Monitoring', 'Accurate', 'Smart Alerts'],
      affiliateUrl: 'https://impact.com/victron?aff_id=YOUR_ID&offer=battery-monitor',
      image: '/images/products/victron-battery-monitor.jpg',
      rating: 4.9,
      reviews: 345,
      badge: 'Premium',
      description: 'The Victron Smart Battery Monitor tracks your battery\'s state of charge, voltage, and current draw with precision. Bluetooth connectivity lets you view data on your phone and get alerts when your battery needs attention.',
      pros: ['Accurate monitoring', 'Bluetooth connectivity', '5-year warranty', 'Smart alerts and notifications'],
      cons: ['Premium price', 'Requires installation', 'Learning curve for full features'],
      bestFor: 'Monitoring battery health, off-grid systems, RV battery management',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-mc4-connectors',
      name: 'Renogy MC4 Connectors (Pair)',
      brand: 'Renogy',
      category: 'Components',
      capacity: null,
      output: null,
      price: 8,
      weight: 0.2,
      dimensions: '3 inch',
      warranty: '1 year',
      ports: ['MC4'],
      charging: ['Solar'],
      features: ['Waterproof', 'Easy Connect', 'Durable'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-mc4',
      image: '/images/products/renogy-mc4-connectors.jpg',
      rating: 4.7,
      reviews: 567,
      badge: null,
      description: 'High-quality MC4 connectors for connecting solar panels in series or parallel. Weatherproof and durable, these connectors ensure a secure, reliable connection for your solar array.',
      pros: ['Waterproof and weather-resistant', 'Easy to connect', 'Durable construction', 'Affordable price'],
      cons: ['Requires crimping tool', 'Limited to MC4 applications', '1-year warranty'],
      bestFor: 'Solar panel connections, expanding solar arrays, system maintenance',
      runtimeEstimate: 'N/A'
    },
    {
      id: 'renogy-solar-mount',
      name: 'Renogy Solar Panel Mounting Brackets',
      brand: 'Renogy',
      category: 'Components',
      capacity: null,
      output: null,
      price: 45,
      weight: 3.5,
      dimensions: '12 x 4 x 2 inches',
      warranty: '2 years',
      ports: [],
      charging: [],
      features: ['Sturdy', 'Adjustable', 'Corrosion Resistant'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-mount',
      image: '/images/products/renogy-solar-mount.jpg',
      rating: 4.6,
      reviews: 234,
      badge: null,
      description: 'Sturdy, adjustable mounting brackets for solar panel installation. Corrosion-resistant construction ensures long-lasting performance on RVs, roofs, or ground mounts.',
      pros: ['Sturdy construction', 'Adjustable angle for optimal sun exposure', 'Corrosion-resistant', 'Complete hardware included'],
      cons: ['Basic design', 'Limited adjustment range', 'Requires tools for installation'],
      bestFor: 'RV solar installation, roof mounting, ground mounts',
      runtimeEstimate: 'N/A'
    }
  ],
  completeKits: [
    {
      id: 'renogy-400w-kit',
      name: 'Renogy 400W Complete Solar Kit',
      brand: 'Renogy',
      category: 'Complete Kits',
      capacity: 2000,
      output: 2000,
      price: 899,
      oldPrice: 1099,
      weight: 55,
      dimensions: 'Complete system',
      warranty: '5 years',
      ports: ['AC', 'USB', 'DC'],
      charging: ['Solar', 'AC'],
      features: ['Complete System', 'Everything Included', 'Easy Install'],
      affiliateUrl: 'https://shareasale.com/r.cfm?b=123&u=YOUR_ID&m=789&afftrack=renogy-400w-kit',
      image: '/images/products/renogy-400w-kit.jpg',
      rating: 4.7,
      reviews: 345,
      badge: 'Best Complete Kit',
      description: 'The Renogy 400W Complete Solar Kit includes everything you need for a full solar installation. Four 100W panels, MPPT charge controller, mounting hardware, cables, and connectors – all in one package.',
      pros: ['Everything included', 'Complete DIY solution', 'MPPT charge controller included', '5-year warranty'],
      cons: ['Requires installation', 'Heavy (55 lbs)', 'No inverter included'],
      bestFor: 'DIY solar installations, RVs, boats, off-grid cabins',
      runtimeEstimate: '400W - 2.4kWh per day'
    },
    {
      id: 'ecoflow-delta-pro-kit',
      name: 'EcoFlow Delta Pro + Solar Panels Kit',
      brand: 'EcoFlow',
      category: 'Complete Kits',
      capacity: 3600,
      output: 3600,
      price: 2999,
      oldPrice: 3499,
      weight: 120,
      dimensions: 'Complete system',
      warranty: '5 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC', 'Car'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Everything Included', 'High Capacity', 'Expandable'],
      affiliateUrl: 'https://impact.com/ecoflow?aff_id=YOUR_ID&offer=delta-pro-kit',
      image: '/images/products/ecoflow-delta-pro-kit.jpg',
      rating: 4.8,
      reviews: 234,
      badge: 'Premium',
      description: 'The ultimate power solution: EcoFlow Delta Pro with matching solar panels. This complete kit provides 3.6kWh of storage with 400W of solar charging capability. Expandable to 25kWh for whole-home backup.',
      pros: ['Massive 3.6kWh capacity', 'Solar panels included', '5-year warranty', 'Expandable system'],
      cons: ['Premium price point', 'Very heavy (120 lbs)', 'Professional installation recommended'],
      bestFor: 'Whole-home backup, emergency preparedness, off-grid living',
      runtimeEstimate: '20+ hours refrigerator'
    },
    {
      id: 'jackery-1000-kit',
      name: 'Jackery Explorer 1000 + SolarSaga Kit',
      brand: 'Jackery',
      category: 'Complete Kits',
      capacity: 1002,
      output: 1000,
      price: 1199,
      oldPrice: 1499,
      weight: 35,
      dimensions: 'Complete system',
      warranty: '2 years',
      ports: ['AC', 'USB-C', 'USB-A', 'DC'],
      charging: ['Solar', 'AC', 'Car'],
      features: ['Portable', 'Everything Included', 'Easy Setup'],
      affiliateUrl: 'https://impact.com/jackery?aff_id=YOUR_ID&offer=explorer-1000-kit',
      image: '/images/products/jackery-1000-kit.jpg',
      rating: 4.9,
      reviews: 567,
      badge: 'Best Value',
      description: 'The Jackery Explorer 1000 kit combines the best-selling power station with portable solar panels. It\'s the perfect portable power solution for camping, RV trips, and emergency backup with everything included and ready to use.',
      pros: ['Complete portable solution', 'Best-selling power station', 'Easy to set up and use', 'Trusted Jackery quality'],
      cons: ['2-year warranty only', 'Limited expansion options', 'Not for whole-home backup'],
      bestFor: 'Camping, RV trips, portable backup, outdoor activities',
      runtimeEstimate: '8-10 hours refrigerator'
    }
  ]
}

export function getProductsByCategory(category) {
  return products[category] || []
}

export function getProductById(id) {
  for (const category of Object.values(products)) {
    const product = category.find(p => p.id === id)
    if (product) return product
  }
  return null
}

export function getRelatedProducts(productId, limit = 3) {
  const allProducts = Object.values(products).flat()
  const currentProduct = getProductById(productId)
  
  if (!currentProduct) return []
  
  const sameCategory = allProducts.filter(p => 
    p.category === currentProduct.category && p.id !== productId
  )
  
  const others = allProducts.filter(p => 
    p.category !== currentProduct.category && p.id !== productId
  )
  
  return [...sameCategory, ...others].slice(0, limit)
}